#!/usr/bin/env bun
/**
 * Generates test/fixtures/v025/{profile/,.connect-state-…,.session-label-…,locks/} —
 * REAL on-disk output from 0.25's own writers (RFC-017 D8/C8: "a committed fixture set
 * per released format proves that N reads N−1"). Run once by hand; its OUTPUT is
 * committed, not regenerated by CI or by `bun run test`.
 *
 *   installation.json, state    — auth/node/store.ts's writeInstallation / writeState
 *   .connect-state-<key>        — connect-store.ts's writeConnectState
 *   .session-label-<key>        — label-store.ts's writeLabelFile
 *   locks/<key>.lock            — server.ts's LockRecord shape (server.ts:3394,
 *                                 3415-3428). server.ts itself cannot be imported here:
 *                                 it has zero exports and runs top-level side effects
 *                                 (see label-store.ts's header), so this reproduces the
 *                                 shape its writeLockExclusive() writes rather than
 *                                 calling it.
 *
 * key.json is NOT a committed fixture — RFC-017's P0 lists installation.json, state,
 * the lock record, connect-store and label-store only; key.json has no format story of
 * its own (auth/node/store.ts treats the whole profile as one unit, gated on
 * installation.json's format). generateSoftwareKey() is used only to give
 * installation.json a real, non-synthetic `jkt`.
 *
 * Usage: bun test/fixtures/generate-v025.ts
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { tmpdir } from "os";
import { fileURLToPath, pathToFileURL } from "url";
import { generateSoftwareKey } from "../../auth/core/signer";
import { makeJoinState } from "../dpop-verify";

const OUT = fileURLToPath(new URL("./v025", import.meta.url));
const SESSION_KEY = "fixture-session";
/** This script's OWN directory — never `process.cwd()` (unknown; the caller can invoke
 * `bun test/fixtures/generate-v025.ts` from anywhere) — used as `git`'s cwd below so the
 * right repository is always found regardless of where this runs from. */
const SCRIPT_DIR = fileURLToPath(new URL(".", import.meta.url));
/** The 0.25.0 release commit these fixtures must be generated FROM — its own hash,
 * because "0.25.0" the tag can move and "0.25" the branch does not exist. */
const FROZEN_AT = "0e7ec8d24167772b2911f9c2efa97ceebda18aed";

/**
 * Finding 5 (2026-09-27 re-review, supersedes finding 12's HEAD/porcelain guard): the
 * repo-root-relative paths of the 0.25 writer modules this script needs, FROZEN at
 * FROZEN_AT — plus auth/node/store.ts's own transitive VALUE dependencies (its one
 * type-only import, `../core/signer`'s `KeyStorage`, is erased by Bun at run time and
 * needs no file on disk). Mirrored into a throwaway tmpdir at these SAME relative
 * paths, so their own relative imports (`../core/jwk` etc.) resolve exactly as they do
 * in the real tree, then imported straight from there.
 *
 * This is what makes a dirty/0.26 working copy structurally unable to leak into a
 * "0.25 fixture": the old guard (assertFrozenCommit, `git status --porcelain` on the
 * whole tree) only ever WARNED that running from the wrong tree would source live
 * 0.26 code — for example 0.26's auth/node/store.ts now writes an RFC-017 `format`
 * field into installation.json (D8) that 0.25 never did, so a run from this very
 * working tree would have silently corrupted the fixture with one. Sourcing these
 * modules from `git show FROZEN_AT:<path>` instead means the code that RUNS is always
 * the 0.25 release's, whatever is on disk right now — the guard has nothing left to
 * protect against.
 */
const FROZEN_FILES = [
  "auth/node/store.ts",
  "connect-store.ts",
  "label-store.ts",
  "auth/core/jwk.ts",
  "auth/core/join-state.ts",
  "auth/core/b64url.ts",
];

/** `git show FROZEN_AT:<path>` for every module in FROZEN_FILES, written into a fresh
 * tmpdir mirroring their real relative layout. Returns the tmp paths of the three
 * actual writer modules the caller imports; the auth/core/* files are dependencies
 * store.ts resolves on its own once it is imported from its mirrored location. */
function freezeWriterModules(): { storeModule: string; connectStoreModule: string; labelStoreModule: string } {
  const tmp = mkdtempSync(join(tmpdir(), "bridge-v025-frozen-"));
  for (const rel of FROZEN_FILES) {
    const proc = Bun.spawnSync(["git", "show", `${FROZEN_AT}:${rel}`], { cwd: SCRIPT_DIR });
    if (!proc.success) {
      throw new Error(`could not read ${rel} at ${FROZEN_AT}: ${new TextDecoder().decode(proc.stderr)}`);
    }
    const dest = join(tmp, rel);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, proc.stdout);
  }
  return {
    storeModule: join(tmp, "auth/node/store.ts"),
    connectStoreModule: join(tmp, "connect-store.ts"),
    labelStoreModule: join(tmp, "label-store.ts"),
  };
}

async function main() {
  const { storeModule, connectStoreModule, labelStoreModule } = freezeWriterModules();
  const store = await import(pathToFileURL(storeModule).href);
  const { writeConnectState } = await import(pathToFileURL(connectStoreModule).href);
  const { writeLabelFile } = await import(pathToFileURL(labelStoreModule).href);

  rmSync(join(OUT, "profile"), { recursive: true, force: true });
  rmSync(join(OUT, "locks"), { recursive: true, force: true });
  rmSync(join(OUT, ".connect-state-" + SESSION_KEY), { force: true });
  rmSync(join(OUT, ".session-label-" + SESSION_KEY), { force: true });
  mkdirSync(OUT, { recursive: true });

  // installation.json + state (auth/node/store.ts, the 0.25 writer, frozen above).
  const profileDir = join(OUT, "profile");
  const { privateJwk, signer } = await generateSoftwareKey();
  store.writeKey(profileDir, privateJwk);
  store.writeState(profileDir, makeJoinState(3));
  store.writeInstallation(profileDir, {
    apiUrl: "https://bridge-api.example.com",
    installationId: "11111111-1111-1111-1111-111111111111",
    installationName: "fixture-machine",
    enrolledAt: 1758000000,
    jkt: signer.jkt,
    keyStorage: "software",
    agent: { id: "22222222-2222-2222-2222-222222222222", handle: "fixture-agent", name: "Fixture Agent" },
    workspace: { id: "33333333-3333-3333-3333-333333333333", name: "Fixture Workspace" },
  });
  rmSync(join(profileDir, "key.json"), { force: true }); // the private key: not a committed fixture, see header

  // connect-store.ts / label-store.ts (also frozen above) — a session's own two files,
  // same STATE_DIR the plugin uses (they are keyed by SESSION_KEY, not by profile).
  writeConnectState(OUT, SESSION_KEY, true);
  writeLabelFile(OUT, SESSION_KEY, "Fixture Session");

  // The session lock record — server.ts's LockRecord shape, reproduced (see header).
  mkdirSync(join(OUT, "locks"), { recursive: true });
  await Bun.write(
    join(OUT, "locks", `${SESSION_KEY}.lock`),
    JSON.stringify({ pid: 4242, procStart: "Mon Jan  1 00:00:00 2024", sessionKey: SESSION_KEY, at: "2024-01-01T00:00:00.000Z" })
  );

  console.log(`wrote v025 fixtures to ${OUT}`);
}

await main();
